[package]
name = "adventofcode-2018"
version = "0.1.0"
authors = ["Tim Peters <zomg.tim@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
image = "*"
petgraph = "0.4"
regex = "1"
time = "0.1"
